---
title: Case Study 2
date: 2025-11-01
author: Group 5 - Zain Naseer, Kevin Stone, Minh Tran
output:
  html_document: default
  pdf_document: default
---

### Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(include = FALSE)
knitr::opts_chunk$set(fig.align = "left")
```

```{r import data}
library(tidyverse)
library(knitr)
library(ggplot2)

base_url <- "https://www.metoffice.gov.uk/pub/data/weather/uk/climate/stationdata/"
output_dir <- "MetOfficeData/"

station_names <- c(
  "Sheffield",
  "Yeovilton",
  "Durham",
  "Heathrow",
  "Newton Rigg",
  "Cambridge",
  "Bradford",
  "Oxford",
  "Sutton Bonington",
  "Waddington",
  "Manston",
  "Shawbury",
  "Ross-on-Wye"
)
station_names_formatted <- tolower(gsub(" ", "", gsub("-", "", station_names)))
all_urls <- paste0(base_url, station_names_formatted, "data.txt")
all_file_paths <- paste0(output_dir, station_names_formatted, "data.txt")

dir.create(output_dir, showWarnings = FALSE)
download.file(all_urls, all_file_paths, method = "libcurl", mode = "wb")

convert_txt_to_df <- function(file_path) {
  # remove row 1-5 and row 7 # nolint
  txt_data <- read_lines(file_path, skip = 5)[-c(2)]
  # clean the text, row by row
  cleaned_txt_data <- txt_data %>%
    str_replace_all("---", "NA") %>%
    str_remove_all("\\*") %>%
    str_remove_all("#") %>%
    str_remove_all("Provisional") %>%
    str_trim()
  # convert into df
  df <- read_table(cleaned_txt_data)
  print(file_path)
  return(df)
}
```

``` {r}
lapply(all_file_paths, convert_txt_to_df)
```
